### ISSUE TITLE
Image Not Displaying in Better Miflora Card on Windows Browser & Mobile (Latest Home Assistant)

### ISSUE THREAD

**Issue by jwall87** [roman-16/better-miflora-card#1]
I used ChatGPT to help me troubleshoot and when all else failed, I've used it to help me articulate the troubleshooting steps i went through:

**Description**
I'm using the Better Miflora Card in Home Assistant (latest version) with my third reality sensor setup. Although my image (FigTree.png) loads fine when accessed directly via /local/FigTree.png, it does not display in the Lovelace card on either my Windows browser or my mobile device.

**Environment**
- Home Assistant Version: Latest (currently running the most recent release)
- Better Miflora Card Version: (v1.1.1)

**Browser(s):**
Windows 11, Vivaldi
Apple IOS, Safari
Installation Method: HACS 

**Steps to Reproduce**
Place the image FigTree.png in the /config/www/ folder.

**YAML Code**
```
type: custom:better-miflora-card
title: "Fig - Fireplace"
image: /local/FigTree.png
min_moisture: 15
max_moisture: 60
min_temperature: 12
entities:
  - entity: sensor.third_reality_soil_sensor_fireplace
    type: moisture
  - entity: sensor.everything_presence_one_6bdd4_illuminance
    type: illuminance
  - entity: sensor.third_reality_soil_sensor_fireplace
    type: temperature
  - entity: sensor.third_reality_soil_sensor_fireplace
    type: battery
```

Confirm the image is accessible by navigating to:
http://<my-ha-address>/local/FigTree.png
The image loads fine in a browser tab.

Refresh the Lovelace dashboard and observe that the image does not display in the card on both Windows and mobile browsers.

**Troubleshooting Steps Taken**
Confirmed that the filename (including case and extension) exactly matches in both the file system and the YAML.
Verified the file is placed in /config/www/.
Tried a different working image used elsewhere in the dashboard.

![Image](https://github.com/user-attachments/assets/23998b6b-a1bc-4024-8e85-be9e079071e9)
